import { InputBody } from '../../support/inputBody';
import { TIMEOUTS } from '../../support/testConfig';

// ─── Calculators ──────────────────────────────────────────────────────────────
const calculators = [
    { title: "01 - Interest Calculator",  description: "This Compound Interest Calculator can help determine the compound interest accumulation and final balances on both fixed principal amounts and additional periodic contributions. There are also optional factors available for consideration, such as the tax on interest income and inflation.", url: "https://www.calculator.net/interest-calculator.html",                          status: 2, site_id: null },
    { title: "01 - Loan Calculator",      description: "In finance, a loan is the transfer of money by one party to another with an agreement to pay it back. The recipient, or borrower, incurs a debt and is usually required to pay interest for the use of the money.",                                                                         url: "https://www.calculator.net/loan-calculator.html",                             status: 2, site_id: null },
    { title: "01 - Mortgage Calculator",  description: "A mortgage loan or simply mortgage, in civil law jurisdictions known also as a hypothec loan, is a loan used either by purchasers of real property to raise funds to buy real estate, or by existing property owners to raise funds for any purpose while putting a lien on the property being mortgaged.", url: "https://www.calculator.net/mortgage-calculator.html",                        status: 2, site_id: null },
    { title: "01 - Payment Calculator",   description: "The Payment Calculator can determine the monthly payment amount or loan term for a fixed interest loan. Use the \"Fixed Term\" tab to calculate the monthly payment of a fixed-term loan. Use the \"Fixed Payments\" tab to calculate the time to pay off a loan with a fixed monthly payment. For more information about or to do calculations specifically for car payments, please use the Auto Loan Calculator. To find net payment of salary after taxes and deductions, use the Take-Home-Pay Calculator.", url: "https://www.calculator.net/payment-calculator.html", status: 2, site_id: 1 },
    { title: "Calculators 11",            description: "this is edited -Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla, mauris laoreet molestie porta, metus mi pretium neque, lacinia accumsan ante lectus eu justo.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed dapibus nunc. Praesent vitae nulla ut nibh dictum ornare. Ut tempor elit quis ex convallis ultricies. Curabitur fermentum accumsan nunc.", url: "http://www.math.com/students/calculators/source/basic.htm",          status: 2, site_id: 1    },
    { title: "Contribution Limit",        description: null,                    url: "http://learnyourbenefits.com/calculators/2019/contribution-limit/index.html",  status: 2, site_id: 1    },
    { title: "Eligible expenses",         description: "test",                  url: "http://learnyourbenefits.com/calculators/2019/eligible-expenses/index.html",   status: 2, site_id: null },
    { title: "Eligible expenses test",    description: "test",                  url: "http://learnyourbenefits.com/calculators/2019/eligible-expenses/index.html",   status: 2, site_id: null },
    { title: "New Calc",                  description: "New calc",              url: "http://www.math.com/students/calculators/source/basic.htm",                    status: 2, site_id: null },
    { title: "One And Only",              description: "d",                     url: "https://www.onlinekhabar.com/",                                                status: 2, site_id: null },
    { title: "Rest",                      description: "sdasd",                 url: "http://www.google.com",                                                        status: 2, site_id: 1    },
    { title: "Sample Calculator",         description: "Testing REGRESSION",    url: "https://admin.learnyourcare.com/manage/sites/new",                             status: 2, site_id: 1    },
];

// ─── Dynamic Calculators ──────────────────────────────────────────────────────
const dynamicCalculators = [
    { title: "Aflac Plad Changes",                    calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/VXaMS2s7", calculator_element: "aflac-calculator-sena-core",          is_global: false, has_custom_fields: true,  thumbnail_url: null },
    { title: "Aflac Voluntary Disability Calculator", calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/A1IVt8R0", calculator_element: "aflac-calculator-core",               is_global: true,  has_custom_fields: false, thumbnail_url: null },
    { title: "Disability calculator changes",         calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/G5CinIjE", calculator_element: "aflac-voluntary-manis-changes",       is_global: false, has_custom_fields: true,  thumbnail_url: null },
    { title: "Disability calculator changes 1",       calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/EHLHqxVj", calculator_element: "aflac-voluntary-manis-changes1",      is_global: false, has_custom_fields: true,  thumbnail_url: null },
    { title: "Dynamic calculator",                    calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/voGiCPXM", calculator_element: "aflac-customization-calculator",      is_global: true,  has_custom_fields: true,  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/temp/documents/ztnOGqKg7BlytVxK2FgxcI9iNLjEAFhlVS5D8AGR.svg" },
    { title: "Invalid Calculator(Corrupt)",           calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/hOSnTx8X", calculator_element: "lyb-local-aflac-se-manis",            is_global: false, has_custom_fields: false, thumbnail_url: null },
    { title: "Old Calc 2024",                         calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/u280divl", calculator_element: "aflac-calculator-sena-old",           is_global: false, has_custom_fields: false, thumbnail_url: null },
    { title: "Pixel Calculator",                      calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/tVEleO7b", calculator_element: "aflac-pixel-calculator",              is_global: false, has_custom_fields: false, thumbnail_url: null },
    { title: "Plad Changes 2024",                     calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/pbbGZFAy", calculator_element: "aflac-calculator-sena-plad",          is_global: false, has_custom_fields: false, thumbnail_url: null },
    { title: "Regression Calculator",                 calculator_url: "https://lycv2.blob.core.windows.net/lycv2/calculators/EJLHDs6p", calculator_element: "aflac-calculator-manish-core",        is_global: false, has_custom_fields: false, thumbnail_url: null },
];

// ─── Documents ────────────────────────────────────────────────────────────────
const iconToType = (icon) => {
    if (icon.includes('excel')) return 'excel';
    if (icon.includes('pdf'))   return 'pdf';
    return 'file';
};

const documents = [
    { title: "11111111",                                 description: "asd", url: "https://lycv2.blob.core.windows.net/lycv2/documents/MapwSJJcIq8apsPrdkPYnz1YUwflxkmbfkFOoGra.xls",  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/MapwSJJcIq8apsPrdkPYnz1YUwflxkmbfkFOoGra_thumb.jpeg",  status: 2, icon: "far fa-file-excel" },
    { title: "cryptographic perspectives",               description: null,  url: "https://lycv2.blob.core.windows.net/lycv2/documents/bRv7HhBqFsC7DUkYiNyCm5pONTN7neYp2ykUSHrj.pdf",  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/bRv7HhBqFsC7DUkYiNyCm5pONTN7neYp2ykUSHrj_thumb.jpeg",  status: 2, icon: "far fa-file-pdf"   },
    { title: "Excel Test",                               description: null,  url: "https://lycv2.blob.core.windows.net/lycv2/documents/L8FvWYDLVrBAm4HAWLj3pFhpVCCv2hecsEftp8nL.xls",  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/L8FvWYDLVrBAm4HAWLj3pFhpVCCv2hecsEftp8nL_thumb.jpeg",  status: 1, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10",                      description: "d",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/9DES851Pb6aRzKqUcsXxmoerTgYAp2TpYnS5kVEq.xls",  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/9DES851Pb6aRzKqUcsXxmoerTgYAp2TpYnS5kVEq_thumb.jpeg",  status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy",               description: "s",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/hxZEETDtK4WewxEqPPvPPyaKUAwTnaMrs57c81ZM.xls",  thumbnail_url: null,                                                                                                     status: 1, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy",               description: "asd", url: "https://lycv2.blob.core.windows.net/lycv2/documents/0JSBwtxiHlMeukieKj9uR7yfhnirHH5HOLLiIsBB.xls",  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/0JSBwtxiHlMeukieKj9uR7yfhnirHH5HOLLiIsBB_thumb.jpeg",  status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy - Copy",        description: "s",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/mM62txecy5Jwj64BXEkAbkpUkMgRyuiq1bM0k6kC.xls",  thumbnail_url: null,                                                                                                     status: 1, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy - Copy",        description: "asd", url: "https://lycv2.blob.core.windows.net/lycv2/documents/nP6sTF67I26FH2ekJQiPoxzjvB3ZdPJ4jua5DUq6.xls",  thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/nP6sTF67I26FH2ekJQiPoxzjvB3ZdPJ4jua5DUq6_thumb.jpeg",  status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy - Copy - Copy", description: "s",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/MbTXpAYn3w3GOOv0pQrjKhJvumIe0w7fwNOjdKSU.xls",  thumbnail_url: null,                                                                                                     status: 1, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy - Copy - Copy", description: "asd", url: "https://lycv2.blob.core.windows.net/lycv2/documents/BK1DCwUNlcaYwv9WkUhjT0xVnKdtyYt6QWDUScp8.xls",  thumbnail_url: null,                                                                                                     status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy (2)",           description: "s",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/HYHw6k3zQ4rkD3ecfnmdVVmQNSY1DeWzfMSIo48e.xls",  thumbnail_url: null,                                                                                                     status: 1, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy (2)",           description: "asd", url: "https://lycv2.blob.core.windows.net/lycv2/documents/Z6M5S98yJ9gDTmY5GqRQNRIMzbjtuedc77JrOpB4.xls",  thumbnail_url: null,                                                                                                     status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy (2) - Copy",    description: "s",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/rFNLka4XvaDf7c1iJmXY0V9Xn1uMqpl3SQ5CW0ob.xls",  thumbnail_url: null,                                                                                                     status: 1, icon: "far fa-file-excel" },
    { title: "file_example_XLS_10 - Copy (2) - Copy",    description: "ad",  url: "https://lycv2.blob.core.windows.net/lycv2/documents/teUQpWEMCxxjYs1MystchmJNbJklGzRZ4SCE8wsg.xls",  thumbnail_url: null,                                                                                                     status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLSX_50",                     description: "asd", url: "https://lycv2.blob.core.windows.net/lycv2/documents/xggqXzw8r91kdyMX9PViJwCZapxUra529hvtgdbS.xlsx", thumbnail_url: null,                                                                                                     status: 2, icon: "far fa-file-excel" },
    { title: "file_example_XLSX_50",                     description: "s",   url: "https://lycv2.blob.core.windows.net/lycv2/documents/3NhQs4srfkF8UQ2Y4lgktcWIZgJ50H9M356NEbPY.xlsx", thumbnail_url: null,                                                                                                     status: 1, icon: "far fa-file-excel" },
].map((doc, i) => ({ ...doc, order: i + 1, type: iconToType(doc.icon) }));

// ─── Images ───────────────────────────────────────────────────────────────────
const images = [
    { title: "Bee",                                description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/TC6gYghVlsv9O6hszJPWBXKDsS47ded1WmY0PrP6.png", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/TC6gYghVlsv9O6hszJPWBXKDsS47ded1WmY0PrP6.png", status: 1, icon: "far fa-image" },
    { title: "Frame",                              description: "Description Test",                   url: "https://lycv2.blob.core.windows.net/lycv2/images/tUILLdn8POekSYkWdhTeZYAqaZIAdITaSWkoj3ka.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/tUILLdn8POekSYkWdhTeZYAqaZIAdITaSWkoj3ka.jpg", status: 2, icon: "far fa-image" },
    { title: "Image 1",                            description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/kBc1rFG1dESemPZTAZXYWSvZ4xrqPz1x7fwIRgsm.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/kBc1rFG1dESemPZTAZXYWSvZ4xrqPz1x7fwIRgsm.jpg", status: 1, icon: "far fa-image" },
    { title: "Image for test",                     description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/LiDYEIQQDiUjp6UjD2pxTcsau44Qez19SsIn5UXx.png", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/LiDYEIQQDiUjp6UjD2pxTcsau44Qez19SsIn5UXx.png", status: 1, icon: "far fa-image" },
    { title: "Panda",                              description: "Description Test",                   url: "https://lycv2.blob.core.windows.net/lycv2/images/nb6LIq3HQcHCiqZHe4SXh7pELe6oz8cCAwpZi8i9.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/nb6LIq3HQcHCiqZHe4SXh7pELe6oz8cCAwpZi8i9.jpg", status: 2, icon: "far fa-image" },
    { title: "pup",                                description: null,                                 url: "https://lycv2.blob.core.windows.net/lycv2/images/GGdciUog2nOEOMPMpgNBjqSjbfRCx4soFUTG4OHO.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/GGdciUog2nOEOMPMpgNBjqSjbfRCx4soFUTG4OHO.jpg", status: 1, icon: "far fa-image" },
    { title: "Sample",                             description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/zJxkc05Dqz1gKiVfiHYH5O79tgKV7d8poPfB1pWF.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/zJxkc05Dqz1gKiVfiHYH5O79tgKV7d8poPfB1pWF.jpg", status: 1, icon: "far fa-image" },
    { title: "Sample Image",                       description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/4KaCYM82x7p26gpeBrXE9JrHKFCZuD0dycZXnJ4h.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/4KaCYM82x7p26gpeBrXE9JrHKFCZuD0dycZXnJ4h.jpg", status: 1, icon: "far fa-image" },
    { title: "Site Image",                         description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/yj1TL2be19Mj5FKMr4XclqXmDZ5yCVwUy7h4yFzL.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/yj1TL2be19Mj5FKMr4XclqXmDZ5yCVwUy7h4yFzL.jpg", status: 1, icon: "far fa-image" },
    { title: "Splash",                             description: "Description Test",                   url: "https://lycv2.blob.core.windows.net/lycv2/images/f7IobwLpIcjsT5klRpODzAcViWu3sgSQiIUy2iNX.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/f7IobwLpIcjsT5klRpODzAcViWu3sgSQiIUy2iNX.jpg", status: 2, icon: "far fa-image" },
    { title: "Test Image",                         description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/F82V2x5IhxYvQk6IQ8Pi27hmtPsWfGwiTjjT3aCK.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/F82V2x5IhxYvQk6IQ8Pi27hmtPsWfGwiTjjT3aCK.jpg", status: 1, icon: "far fa-image" },
    { title: "TestDog-Global-6500651592022290778", description: "TestDog-Global-6500651592022290778", url: "https://lycv2.blob.core.windows.net/lycv2/images/tm7RMu7Z4vSp5bQ4w4qFXCPvnAXXjJv1cPPCYYKY.png", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/tm7RMu7Z4vSp5bQ4w4qFXCPvnAXXjJv1cPPCYYKY.png", status: 2, icon: "far fa-image" },
    { title: "Today",                              description: "Description as sample",              url: "https://lycv2.blob.core.windows.net/lycv2/images/dcLgUHKQEqChkKm7M5c4TsrawrPC85QgAE27QLAD.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/dcLgUHKQEqChkKm7M5c4TsrawrPC85QgAE27QLAD.jpg", status: 1, icon: "far fa-image" },
    { title: "Unsplash",                           description: "Description Test",                   url: "https://lycv2.blob.core.windows.net/lycv2/images/nSErXL8B8n22L2iUQVTjw1eI8fCgPeNUAa0psbnP.jpg", thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/nSErXL8B8n22L2iUQVTjw1eI8fCgPeNUAa0psbnP.jpg", status: 2, icon: "far fa-image" },
].map((img, i) => ({ ...img, order: i + 1 }));

// ─── Videos ───────────────────────────────────────────────────────────────────
const videos = [
    { title: "00 - Super ninja test",        description: "!! Important !! \nPlease do not edit or modify this video.\n\"Super ninja video\"",                                                                                                                                                                                                                                                                                             author: null, duration: 17,  size: null, video_url: "https://player.vimeo.com/video/923313380",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/RBLipMPBKsrUo7uK087vjQpsUoZXbqSPeeJ2gh7P.png", status: 2 },
    { title: "1 - Template Test1234",         description: "Video template test video- July 19",                                                                                                                                                                                                                                                                                                                                                author: null, duration: 23,  size: null, video_url: "https://player.vimeo.com/video/731305166",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/8aTjgRYMm7A7rMvXIiU8ymEiwSTHTOrxUnuD0fXA.jpg", status: 2 },
    { title: "1 External video local cdn",    description: "cdn video",                                                                                                                                                                                                                                                                                                                                                                        author: null, duration: null, size: null, video_url: "https://lyc-ade0bvfkbgf8ghgz.z03.azurefd.net/lycv2/videos/65f2e84767b31.mp4",    video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/woVmyQ1gtrL7eME8CFgPjUCp6YMDYgXze9mrwCs5.png", status: 2 },
    { title: "1 vimeo video update",          description: "Test",                                                                                                                                                                                                                                                                                                                                                                             author: null, duration: 267, size: null, video_url: "https://player.vimeo.com/video/842492503",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/uhkoS33IG3EHIf26gFSKJlODB3grH0hFkMWhHzO2.png", status: 2 },
    { title: "1000 test edit",                description: "This is test. test",                                                                                                                                                                                                                                                                                                                                                               author: null, duration: 220, size: null, video_url: "https://player.vimeo.com/video/277535214",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/6Z4xU38L1gkY56t5mT2hIK4brjTWIO4wUmU6cuVR.png", status: 2 },
    { title: "1000-1 test",                   description: "Testing video",                                                                                                                                                                                                                                                                                                                                                                    author: null, duration: 220, size: null, video_url: "https://player.vimeo.com/video/277535214",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/PhKSN4EZ7ADnsdtCGFvM8F1KfZyz4mrTaATM2L6k.png", status: 2 },
    { title: "100001 bunny Sample Video",     description: "test",                                                                                                                                                                                                                                                                                                                                                                             author: null, duration: null, size: null, video_url: "https://vimeo.com/347119375",                                                       video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/ZaEEqA9cV0bzmtRAeH79O75CyTKhogucFVG2LFbh.png", status: 2 },
    { title: "10001 Video edit",              description: "Edit-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla, mauris laoreet molestie porta, metus mi pretium neque, lacinia accumsan ante lectus eu justo.",                                                                                                                                                                                                       author: null, duration: 48,  size: null, video_url: "https://player.vimeo.com/video/730951568",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/lhkpYn8o5geWeBV6ceWpuzAsBLEAPElQoBrQodAx.png", status: 2 },
    { title: "10001 Video edit",              description: "Edit-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla, mauris laoreet molestie porta, metus mi pretium neque, lacinia accumsan ante lectus eu justo.",                                                                                                                                                                                                       author: null, duration: 48,  size: null, video_url: "https://player.vimeo.com/video/670786127",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/4d9TQKS7Wrhv47hPLHU03Dtjt0xSg3WtlAGC4chj.jpg", status: 2 },
    { title: "100011 test edit",              description: "Nunc tempor pharetra venenatis. Etiam dictum turpis at aliquam malesuada. Aenean sit amet orci vitae massa suscipit blandit eu eu sapien. Curabitur orci libero, feugiat quis ligula efficitur, porttitor varius nunc. Sed fringilla libero sed auctor luctus. Proin eu malesuada purus, scelerisque efficitur quam. Nulla nulla justo, venenatis ut blandit nec, interdum a nulla.", author: null, duration: 48,  size: null, video_url: "https://player.vimeo.com/video/388209530",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/y62ShBHFzie9tHn9ry3aH5Vm4lgolsT5EGgOD766.jpg", status: 2 },
    { title: "1001 external link",            description: "vvv",                                                                                                                                                                                                                                                                                                                                                                              author: null, duration: null, size: null, video_url: "https://admin.learnyourcare.com/manage/sites/559/page-and-resources",             video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/GPcqulosV9qcK93nu7DM8WAlPMX6HF1a97Kzd9I7.png", status: 1 },
    { title: "1001 fb",                       description: "https://www.facebook.com/watch?v=3229308587218288",                                                                                                                                                                                                                                                                                                                                 author: null, duration: null, size: null, video_url: "https://www.facebook.com/watch?v=3229308587218288",                                 video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/ctFjb8xfw8zmBEjlKrW0HsyepimOdBoiLCzW3qxl.png", status: 1 },
    { title: "1001 test",                     description: "test",                                                                                                                                                                                                                                                                                                                                                                             author: null, duration: 27,  size: null, video_url: "https://player.vimeo.com/video/657712769",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/LswCsqyQ0yeKyg6zNa3r3Ft8GQJhVKWu0gOE6uCe.png", status: 2 },
    { title: "10011 Template",                description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla, mauris laoreet molestie porta, metus mi pretium neque, lacinia accumsan ante lectus eu justo.",                                                                                                                                                                                                            author: null, duration: 110, size: null, video_url: "https://player.vimeo.com/video/277534261",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/IMQXYGSJKQ7kGXQFbfIV97GMUlgzZksk23Cfy2Yk.png", status: 2 },
    { title: "101 finale",                    description: "101 finale",                                                                                                                                                                                                                                                                                                                                                                       author: null, duration: 150, size: null, video_url: "https://player.vimeo.com/video/1143723943",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/WmfY2ZLBudcb2ylszsVWb7Ov0K5tqroo4j7mpzeO.png", status: 2 },
    { title: "1011 test edited",              description: "Test",                                                                                                                                                                                                                                                                                                                                                                             author: null, duration: 4,   size: null, video_url: "https://player.vimeo.com/video/646808085",                                          video_thumbnail_url: "https://lycv2.blob.core.windows.net/lycv2/images/Y3QFYRSZ9qaro9i0T7DPQ59xrLRYKitcGXShvy0n.jpg", status: 2 },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
const responseTimeLimit = TIMEOUTS.response;

const assertResponse = (response, statuses = [200], checkDuration = false) => {
    cy.log(`Status: ${response.status} | Body: ${JSON.stringify(response.body)}`);
    expect(response.status).to.be.oneOf(statuses);
    if (checkDuration) expect(response.duration).to.be.lessThan(responseTimeLimit);
};

const seedEach = (label, items, endpoint, buildBody) => {
    items.forEach((item, i) => {
        it(`[${i + 1}/${items.length}] should seed ${label}: "${item.title}"`, () => {
            cy.Post(endpoint, buildBody(item), { failOnStatusCode: false })
                .then((r) => assertResponse(r, [200, 201]));
        });
    });
};

// ─── Seed Suite ───────────────────────────────────────────────────────────────
describe('Seed Resources', () => {
    before(() => cy.loginAndGetToken());

    describe('Seed Documents', () => {
        it(`should seed ${documents.length} documents`, () => {
            cy.Post('/v2/documents/multiple', InputBody.documentsMultiple(documents), { failOnStatusCode: false })
                .then((r) => assertResponse(r, [200], true));
        });
    });

    describe('Seed Images', () => {
        it(`should seed ${images.length} images`, () => {
            cy.Post('/v2/images/multiple', InputBody.imagesMultiple(images), { failOnStatusCode: false })
                .then((r) => assertResponse(r, [200], true));
        });
    });

    describe('Seed Videos', () => {
        seedEach('video', videos, '/videos',
            ({ title, description, author, duration, size, video_url, video_thumbnail_url, status }) =>
                InputBody.video(title, description, author, duration, size, video_url, video_thumbnail_url, status)
        );
    });

    describe('Seed Calculators', () => {
        seedEach('calculator', calculators, '/calculators',
            ({ title, description, url, status, site_id }) => ({ title, description, url, status, site_id })
        );
    });

    describe('Seed Dynamic Calculators', () => {
        seedEach('dynamic calculator', dynamicCalculators, '/dynamic-calculators',
            ({ title, calculator_url, calculator_element, is_global, has_custom_fields, thumbnail_url }) =>
                ({ title, calculator_url, calculator_element, is_global, has_custom_fields, thumbnail_url })
        );
    });
});
